<?php
$jobListings = [
  [
    'user_id' => 1,
    'title' => '软件工程师',
    'description' => '我们正在寻找一位熟练的软件工程师来开发高质量的软件解决方案',
    'salary' => '90000',
    'tags' => '开发, 编程, Java, Python',
    'company' => '科技解决方案有限公司',
    'address' => '主街123号',
    'city' => '广州',
    'state' => '广东',
    'phone' => '348-334-3949',
    'email' => 'info@techsolutions.com',
    'requirements' => '计算机科学或相关领域的学士学位，3年以上软件开发经验',
    'benefits' => '医疗保险, 401(k)计划配对, 灵活工作时间'
  ],
  [
    'user_id' => 2,
    'title' => '市场专员',
    'description' => '我们正在寻找一位市场专员来创建和管理市场营销活动',
    'salary' => '70000',
    'tags' => '市场营销, 广告',
    'company' => '市场达人',
    'address' => '市场街456号',
    'city' => '深圳',
    'state' => '广东',
    'phone' => '454-344-3344',
    'email' => 'info@marketingpros.com',
    'requirements' => '市场营销或相关领域的学士学位，数字营销经验',
    'benefits' => '健康和牙齿保险, 带薪休假, 远程工作选项'
  ],
  [
    'user_id' => 3,
    'title' => '网页开发者',
    'description' => '加入我们的团队，作为网页开发者，创建惊艳的网络应用程序',
    'salary' => '85000',
    'tags' => '网页开发, 编程',
    'company' => '网技解决方案',
    'address' => '网络大道789号',
    'city' => '广州',
    'state' => '广东',
    'phone' => '456-876-5432',
    'email' => 'info@webtechsolutions.com',
    'requirements' => '计算机科学或相关领域的学士学位，精通HTML, CSS, JavaScript',
    'benefits' => '竞争性薪资, 专业发展机会, 友好的工作环境'
  ],
  [
    'user_id' => 4,
    'title' => '数据分析师',
    'description' => '我们正在招聘一名数据分析师，分析和解读数据以获得洞察',
    'salary' => '75000',
    'tags' => '数据分析, 统计',
    'company' => '数据洞察有限责任公司',
    'address' => '数据街101号',
    'city' => '广州',
    'state' => '广东',
    'phone' => '444-555-5555',
    'email' => 'info@datainsights.com',
    'requirements' => '数据科学或相关领域的学士学位，强大的分析技能',
    'benefits' => '健康福利, 远程工作选项, 休闲着装'
  ],
  [
    'user_id' => 5,
    'title' => '平面设计师',
    'description' => '加入我们的创意团队，作为平面设计师，将想法变为现实',
    'salary' => '70000',
    'tags' => '平面设计, 创意',
    'company' => '创意作品有限公司',
    'address' => '设计大道234号',
    'city' => '广州',
    'state' => '广东',
    'phone' => '499-321-9876',
    'email' => 'info@creativeworks.com',
    'requirements' => '平面设计或相关领域的学士学位，精通Adobe Creative Suite',
    'benefits' => '灵活工作时间, 创意工作环境, 成长机会'
  ],
  [
    'user_id' => 6,
    'title' => '数据科学家',
    'description' => '我们正在寻找一名数据科学家，分析复杂数据并生成洞察',
    'salary' => '100000',
    'tags' => '数据科学, 机器学习',
    'company' => '数据天才公司',
    'address' => '数据驱动567号',
    'city' => '深圳',
    'state' => '广东',
    'phone' => '684-789-1234',
    'email' => 'info@datagenius.com',
    'requirements' => '数据科学或相关领域的硕士或博士学位，机器学习算法经验',
    'benefits' => '竞争性薪资, 远程工作选项, 专业发展'
  ],
];
